### PR TITLE
Writing unit testing for add/remove function

### PR DESCRIPTION
**Pull request by mohammadamin-alizadeh**
The things that we did on this PR:

1. Use the jest framework for testing.
2. Create a test file (addRemove.test.js) for a file containing the add item and delete item functions that you want to test.
3. Mock a storage object to "imitate" localStorage operations 
4. Mock HTML to test if add/delete functions add or remove exactly one <li> element to/from the list in the DOM.

### CODE REVIEW

**Review by AbelG101 — COMMENTED** [review]
# Hi @musangamfure & @M-AminAlizadeh  👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that doesn't have substantial commits from your coding partner @M-AminAlizadeh, please make sure both of you contribute enough code as this is a pair programming activity. 
- **REMOVING A FILE DOESN'T COUNT AS A CONTRIBUTION.** 😅

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by AbelG101 — COMMENTED** [review]
# Hi @musangamfure & @M-AminAlizadeh 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] As I've mentioned previously please make sure to have substantial commits from @M-AminAlizadeh as he hasn't made any contributions to the code base.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Shisui6 — COMMENTED** [review]
Hi @M-AminAlizadeh and @musangamfure, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted the project `Testing To Do list - part 1` using the submission link for the project `Testing To Do list - part 2`. Please note that these are different milestones and contain different requirements. Please make sure to submit the correct project using the correct link

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @musangamfure        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯
- [x] Tests running correctly 💯 
 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

[OPTIONAL] It would be nice to add your coding partners contact infomation to the Authors section because this is a pair programming exercise.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Pull request merged**
